@startuml
skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 60
skinparam sequenceParticipant underline
actor 图书管理员
actor "读者" as a
participant "登陆" as b
participant "挂失记录" as c

activate 图书管理员
图书管理员 -> b: 登陆系统
activate b
deactivate b
图书管理员 -> a: 验证读者信息
activate a
a->c:登记挂失记录
deactivate a
activate c
图书管理员 -> a:借书卡已挂失
activate a
deactivate c
deactivate a

@enduml