@startuml
actor 图书管理员
actor 读者
actor 工作人员
actor  游客
rectangle 图书馆系统 {
图书管理员 -> (登陆)
图书管理员 -> (购入图书)
图书管理员 -> (借出图书)
(借出图书) <. (验证读者信息): include
(检查是否超出可借数量) .> (借出图书) : include
(借出图书) <.(修改图书库存): include
图书管理员 -> (续借)
(续借) <. (验证读者信息): include
(归还图书) <- 图书管理员
(归还图书) <.(是否逾期): include
(是否逾期) <.(罚款): entend
(整理书籍) -> (工作人员)
(归还图书) <. (验证读者信息): include
(检查可借数量是否正确) .> (归还图书) : include
(归还图书) <.(修改图书库存): include
图书管理员 --> (维护图书)
图书管理员 --> (维护读者信息)
(查询书目) <-- 读者
(查询书目) <-- 游客
(查询借阅情况) <--读者
(预定图书).>(查询书目):include
(取消预定).>(查询书目):include
(借书卡挂失) <-读者
(登陆) <- 读者
(身份验证) .>(登陆)
}
@enduml