@startuml
left to right direction
skinparam packageStyle rect
actor 图书管理员
actor 读者
rectangle 借出图书 {
图书管理员 --> (借出图书)
(借出图书) <. (验证读者信息): 包含
(检查是否超出可借数量) .> (借出图书) : 包含
(借出图书) <.(修改图书库存): 包含
(借出图书)--> 读者
}
@enduml