@startuml

abstract class 图书信息
abstract 查找图书
interface 预借图书
interface 登陆
interface 读者
interface 管理员
interface 归还图书
interface 逾期罚款
逾期罚款 --|> 归还图书
图书信息 --o  查找图书
图书信息 <--  预借图书
图书信息 <--  归还图书
登陆 <|-- 管理员
登陆 <|-- 读者
管理员 ..|> 查找图书
读者 ..|> 查找图书
登陆 "1..*" -- "0..n" 管理员
登陆 "1..*" -- "0..n" 读者
查找图书 "1..*" -- "0..n" 图书信息
预借图书 "1..*" -- "0..n" 图书信息
归还图书 "1..*" -- "0..n" 图书信息
归还图书 "1..*" -- "1..*" 逾期罚款
读者 "0..n*" -- "0..n" 管理员
读者 "1..*" -- "0..n"  查找图书
管理员"1..*" -- "0..n" 查找图书
class 图书信息 {
-书名
-作者
-ISBN
-书的总数量
-已借出数量
-书的种类
查询()
增添()
修改()
删除()
借书()
归还()
续借()
预借()
}

class 登陆 {
-用户名
-密码
修改用户信息()
修改密码()
}

class 查找图书 {
-书名
-作者
-ISBN
-书的种类
-显示图书信息
借书()
归还()
续借()
预借()
取消预借()

}

class 预借图书 {
-显示图书信息
-预借时间
-预借数量
-修改预借
创建预借对象()
修改预借对象()
删除预借对象()
}

class 读者{
-姓名
-账号
-借阅证编码
-可借出书本的总数量
-已借出数量
-借出书本信息
-借书卡挂失
查询()
借书()
归还()
续借()
预借()
}

class 管理员{
-姓名
-账号
-借书卡挂失处理
查询()
}

class 归还图书 {
-书名
-作者
-ISBN
-书的种类
-显示图书信息
-显示读者信息
-逾期罚款
预借()
取消预借()
交罚款()
}

class 逾期罚款 {
交罚款()
}
@enduml