@startuml

object 预借图书 {

显示图书信息
预借时间:2019-4-6
预借数量:3
修改预借

}

预借图书 <|-- 图书信息
查找图书 <|-- 预借图书
object 查找图书 {
书名:《信息系统分析与设计》
作者:
ISBN:
书的种类:
显示图书信息:
}
查找图书 <|-- 图书信息

object 图书信息 {
书名:《信息系统分析与设计》
作者:王晓敏
ISBN:978-7-5606-3921-5
书的总数量:600
已借出数量:199
书的种类:IT类
}

@enduml