@startuml

object 归还图书 {
书名:《信息系统分析与设计》
作者:王晓敏
ISBN:978-7-5606-3921-5
书的总数量:600
已借出数量:199
书的种类:IT类
显示读者信息
逾期罚款
}
归还图书 <|-- 逾期罚款
object 逾期罚款 {
交罚款
}
object 读者{
姓名:程瑞
账号:201610414405
借阅证编码:123456
借出书本的总数量:10
已借出数量:3
借出书本信息:《信息系统分析与设计》,
《Linux程序设计与基础》,《Java程序设计》
借书卡挂失
}
归还图书 <|--读者
@enduml